blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from marketing.views import email_list_signup
from django.contrib.auth import views as auth_views
from posts.views import search,blog,post \
,index,mypage,post_delete,post_update,category,categorydetail,\
instance,instance_detail,city_list,default_map,\
area_list,area_details,register,logout_view,myuser,send_otp_this,otp_match,\
login_view,send_email,filter_dropdown2,PostListView,PostUpdateView,PostCreateView,\
load_cities,load_categories,mypost,profile,MembershipSelectView,\
PaymentView,updateTransactions


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name="index"),
    path('sms/', send_otp_this,name="sms"),
    path('otp-match/',otp_match,name='otp-match'),
    path('login/',login_view,name = "login"),
    path('logout/',logout_view,name = "logout"),
    path('blog/', blog, name = 'post-list'),
    path('post/<id>/', post,name='post-detail'),
    path('post/<id>/mypost', mypost,name='mypost'),
    path('post/<id>/update/', post_update ,name='post-update'),
    path('post/<id>/delete/', post_delete ,name='post-delete'),
    path('category/',category,name='category-list'),
    path('city-list/',city_list,name='city-list'),
    # path('district-list/<id>/',district_list,name='district-list'),
    path('area-list/<id>/',area_list,name='area-list'),
    path('area-details/<id>/',area_details,name='area-details'),
    # path('city-details/<id>/',city_details,name='city-details'),
    path('map/',default_map,name='default_map'),
    # path('district-details/<id>/',district_details,name='district-details'),
    # path('category/<id>/',categorydetail,name='category-detail'),
    path('category/<id>/',instance,name='category-detail'),
    # path('instance/<id>/',instance,name='instance'),
    path('instancedetail/<id>/',instance_detail,name='instance-detail'),
    # path('accounts/',include('django.contrib.auth.urls')),
    # path('accounts/password_reset/',password_reset,name='password_reset'),
    # path('accounts/password_reset_done/',password_reset_done,name='password_reset_done'),

    path('profile/',profile,name='profile'),
    path('mypage/',mypage,name='mypage'),
    path('myuser/',myuser,name='myuser'),
    path('register/', register, name='register'),
    # path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('search/', search,name='search'),
    path('subscribe/', email_list_signup, name='subscribe'),
    path('tinymce/', include('tinymce.urls')),
    # path('post/',product_create_view, name = 'product_create_view'),
    path('send/', send_email,name='send_email'),
    path('filter_dropdown2/', filter_dropdown2, name='filter_dropdown2'),

    path('', PostListView.as_view(), name='post_changelist'),
    path('post/', PostCreateView.as_view(), name='post_add'),
    path('<int:pk>/', PostUpdateView.as_view(), name='post_change'),
    path('ajax/load-cities/', load_cities, name='ajax_load_cities'),
    path('ajax/load-categories/', load_categories, name='ajax_load_categories'),
    path('membership/', MembershipSelectView.as_view(), name='select'),
    path('payment/', PaymentView, name='payment' ),
    path('update-transactions/<subscription_id >/', updateTransactions, name = 'update-transactions'),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.urls import reverse
from tinymce import HTMLField
from PIL import Image
from localflavor.br.br_states import STATE_CHOICES
import random
# User = get_user_model()
from django.contrib.auth.models import (
    AbstractBaseUser,BaseUserManager
   )
USERNAME_REGEX = '^[a-zA-Z0-9.+-]*$'

class UserManager(BaseUserManager):
    def create_user(self,username,email, phone, password=None, is_staff = False, is_active=True, is_admin=False):

        if not username:
            raise ValueError('Users must have an email address')
        if not email:
            raise ValueError('Users must have an email address')

        if not phone:
            raise ValueError('users must have a phone number')

        user  = self.model(
             username = username,
             email = self.normalize_email(email),
             phone=phone
        )
        user.set_password(password)
        user.staff = is_staff
        user.admin = is_admin
        user.active = is_active
        user.save(using = self._db)
        return user

    # def create_staffuser(self, phone,username, email, password=None):
    #     user = self.create_user(
    #      phone,
    #      username,
    #      email,
    #      password=password,
    #      is_staff = True,
    #     )
    #     return user

    # def create_superuser(self,username,email,password=None):
    #     user = self.create_user(username,email,password=password)
    #     user.is_admin = True
    #     user.is_staff = True
    #     user.save(using=self._db)
    #     return user

    def create_superuser(self,username, password=None, is_staff = True, is_active=True, is_admin=True):

        # if not email:
        #     raise ValueError('Users must have an email address')

        # if not phone:
        #     raise ValueError('users must have a phone number')

        user  = self.model(
             username = username,
             # email = self.normalize_email(email),
             # phone=phone
        )
        user.set_password(password)
        user.staff = is_staff
        user.admin = is_admin
        user.active = is_active
        user.save(using = self._db)
        return user

class User(AbstractBaseUser):
    username = models.CharField(
                     max_length=300,
                     validators =[
                        RegexValidator(regex = USERNAME_REGEX,
                                         message = 'Username must be alphanumeric or contain numbers',
                                         code = 'invalid_username'
                              )],
                     unique = True
                )
    email = models.EmailField(
            max_length=255,
            unique=True,
            verbose_name='email address'
       )
    phone_regex = RegexValidator(regex  =r'^\+?1?\d{9,14}$',
      message = "phone number must be in format: '+9999999'")
    phone = models.CharField(validators=[phone_regex], max_length = 15,unique = True)
    # name   = models.CharField(max_length=20, blank=True,null=True)
    first_login = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    staff  =models.BooleanField(default =False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELD = ['email']

    objects = UserManager()

    def __str__(self):
        return self.username

    # def get_username():
    #     return self.username


    def get_full_name(self):

           return self.username


    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

    # def get_absolute_url(self):
    #
    #     return reverse("mypage",
    #         kwargs={
    #         'id':self.id
    #     })
    #
    # @property
    # def get_posts(self):
    #     return self.posts.all()




MEMBERSHIP_CHOICES = (
('Enterprise','ent'),
('Professional','pro'),
('Free','free')
)



class Membership(models.Model):

   slug = models.SlugField()
   membership_type = models.CharField(
   choices=MEMBERSHIP_CHOICES,
   default='Free',
   max_length=30)
   price = models.IntegerField(default=15)
   plan_id = models.CharField(max_length=40)

   def __str__(self):
       return self.membership_type

class UserMembership(models.Model):

   user = models.ForeignKey(User,on_delete=models.SET_NULL ,blank=True,null=True)
   customer_id = models.CharField(max_length=40)
   membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

   def __str__(self):
       return self.user.username

def post_save_usermembership_create(sender,instance,created, *args, **kwargs):
       if created:

          UserMembership.objects.get_or_create(user = instance)
          user_membership, created = UserMembership.objects.get_or_create(user = instance)
          if user_membership.customer_id is None or user_membership.customer_id == '':

             new_customer_id =random.randint(999, 9999)

             user_membership.customer_id = new_customer_id
             user_membership.save()

post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)

class Subscription (models.Model):

   user_membership = models.ForeignKey(UserMembership,on_delete=models.CASCADE)
   subscription_id = models.CharField(max_length=40)
   active = models.BooleanField(default=True)

   def __str__(self):
       return self.user_membership.user.username





class PhoneOTP(models.Model):
    phone_regex = RegexValidator(regex = r'^\+?1?\d{9,14}$',message="Phone number must be enter")
    phone       = models.CharField(validators=[phone_regex], max_length=17,unique=True)
    otp         = models.CharField(max_length= 9 ,blank=True,null=True)
    count       = models.IntegerField(default =0,help_text = 'Number of otp sent')
    # logged      = models.BooleanField(default = False,help_text = 'if otp verification got successful')
    # forgot      = models.BooleanField(default = False,help_text = 'only true for forgot password ')
    # forgot_logged      = models.BooleanField(default = False,help_text = 'only true if validdate otp forgot get ')

    def __str__(self):
        return str(self.phone) + 'is sent' + str(self.otp)







class Author(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1, on_delete=models.SET_NULL ,blank=True,null=True)
    profile_picture = models.ImageField()
    email = models.EmailField()
    # user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
    # user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):

        return reverse("mypage",
        kwargs={
        'id':self.id
        })

    @property
    def get_posts(self):
        return self.posts.all()


# @receiver(post_save, sender=User)
# def author_qs(sender,**kwargs):
#     if kwargs.get('created',False):
#         Author.objects.create(user=kwargs.get('instance'))


class Category(models.Model):
    title = models.CharField(max_length = 50)

    def __str__(self):
        return self.title


    def get_absolute_url(self):

        return reverse("category-detail",
        kwargs={
        'id':self.id
        })

    # def get_absolute_url(self):
    #
    #     return reverse("product_create_view",
    #     kwargs={
    #     'id':self.id
    #     })


    @property
    def get_posts(self):
        return self.posts.all()

    @property
    def get_instances(self):
        return self.instances.all()



class Instance(models.Model):
    title = models.CharField(max_length=100)
    # category = models.ManyToManyField(Category)
    category = models.ForeignKey(Category, related_name='instances', on_delete= models.CASCADE)

    def __str__(self):
        return self.title


    def get_absolute_url(self):

        return reverse("instance-detail",
        kwargs={
        'id':self.id
        })

    @property
    def get_posts(self):
        return self.posts.all()



class City(models.Model):
    title = models.CharField(max_length=50)
    # uf = models.CharField('UF', max_length=2, choices=STATE_CHOICES)

    def __str__(self):
        return self.title

# class Meta:
#     ordering = ('title',)
#     verbose_name = 'city'
#     verbose_name_plural = 'cities'





    @property
    def get_posts(self):
        return self.posts.all()


    @property
    def get_areas(self):
        return self.areas.all()



    def get_absolute_url(self):

        return reverse('area-list', kwargs={

         'id':self.id })





class Area(models.Model):
    title = models.CharField(max_length=50)
    city = models.ForeignKey(City, related_name='areas', on_delete= models.CASCADE)


    def __str__(self):
        return self.title

    @property
    def get_posts(self):
        return self.posts.all()


    def get_absolute_url(self):

        return reverse('area-details', kwargs={

         'id':self.id })





class Post(models.Model):
    # user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1 ,on_delete=models.SET_NULL ,blank=True,null=True)
    user = models.ForeignKey(User,on_delete=models.SET_NULL ,blank=True,null=True)

    title = models.CharField(max_length=30)
    # instance = models.ManyToManyField(Instance)

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br><br>


{% for cat in category %}
  <div>

  <h2>  <a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a></h2>


  </div>
  <br/>
{% endfor %}
<!-- {% for ins in instance %}
  <div>

  <h2>  <a href="/">{{ ins.title }}</a></h2>


  </div>
  <br/>
{% endfor %} -->


  <br><br><br>


{% endblock content %}

templates/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8">
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in queryset %}
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url}}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{ post.timestamp|timesince}}</div>
                    {% for cat in post.categoreis.all %}
                    <div class="category">
                      <a href="#">{{ cat }}</a>
                    </div>
                    {% endfor %}
                  </div><a href="{{ post.get_absolute_url }}">
                    <h3 class="h4">{{ post.title }}</h3></a>
                  <p class="text-muted">{{ post.overview }}</p>
                  <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                      <div class="title"><span>{{ post.author.user.username}}</span></div></a>
                    <div class="date"><i class="icon-clock"></i>{{post.timestamp|timesince}} ago</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                  </footer>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </main>
        {% include 'sidebar.html' with most_recent=most_recent  category_count=category_count  %}
      </div>
    </div>


 {% endblock content %}

templates/category_detail1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  {% for post in queryset.get_posts %}
  
      <div class="post col-xl-6">
        <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url}}" alt="..." class="img-fluid"></a></div>
        <div class="post-details">
          <div class="post-meta d-flex justify-content-between">
            <div class="date meta-last">{{ post.timestamp|timesince}}</div>
            {% for cat in post.categoreis.all %}
            <div class="category">
              <a href="#">{{ cat }}</a>
            </div>
            {% endfor %}
            </div><a href="{{ post.get_absolute_url }}">
            <h3 class="h4">{{ post.title }}</h3></a>
          <p class="text-muted">{{ post.overview }}</p>
          <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
              <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
              <div class="title"><span>{{ post.author.user.username}}</span></div></a>
            <div class="date"><i class="icon-clock"></i>{{post.timestamp|timesince}} ago</div>
            <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
          </footer>
        </div>
      </div>
  {% endfor %}













 {% endblock content %}

templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for area in areas %}
<option value="{{ area.pk }}">{{ area.title }}</option>
{% endfor %}

templates/city_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class = "container">
   <div class = "column">
     <br/><br/><br/>
     <h2>list of city :</h2>
     <br/>
      {% for city in city_qs  %}
         <h3><a href = "{{ city.get_absolute_url }}"> city:{{city.title}}</a></h3>
         <br/><br/><br/>
      {% endfor %}

  </div>
</div>















 {% endblock content %}

templates/default.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Display and style rich text labels</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v3.1.6/mapbox-gl-geocoder.min.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v3.1.6/mapbox-gl-geocoder.css' type='text/css' />
<style>
.geocoder {
  position:absolute;
  z-index:1;
  width:50%;
  left:50%;
  margin-left:-25%;
  top:20px;
}
.mapboxgl-ctrl-geocoder { min-width:100%; }
</style>
<style>
.coordinates {
  background: rgba(0,0,0,0.5);
  color: #fff;
  /* color: red; */
  position: absolute;
  bottom: 40px;
  left: 10px;
  padding:5px 10px;
  margin: 0;
  font-size: 11px;
  line-height: 18px;
  border-radius: 3px;
  display: none;
}
</style>


<div id='map'></div>
<pre id='info'></pre>
<pre id='coordinates' class='coordinates'></pre>
<div id='geocoder' class='geocoder'></div>


<script>
mapboxgl.accessToken = 'pk.eyJ1IjoibWhmZDI4IiwiYSI6ImNqdHZtZXhxZTFzbmo0M3BjdmRoMHhyaDUifQ.iptJuYP1nlA5BhBiKKlYdg';
mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.0/mapbox-gl-rtl-text.js');
var coordinates = document.getElementById('coordinates');
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
    center: [51.3890, 35.6892], // starting position [lng, lat]
    zoom: 12 // starting zoom
});



map.on('load', function() {
    map.setLayoutProperty('country-label', 'text-field', ['format',
        ['get', 'name_en'], { 'font-scale': 1.2 },
        '\n', {},
        ['get', 'name'], {
            'font-scale': 0.8,
            'text-font': ['literal', [ 'DIN Offc Pro Italic', 'Arial Unicode MS Regular' ]]
        }
    ]);

});

map.addControl(new mapboxgl.NavigationControl());



var geocoder = new MapboxGeocoder({
accessToken: mapboxgl.accessToken
});

document.getElementById('geocoder').appendChild(geocoder.onAdd(map));


var marker = new mapboxgl.Marker({
    draggable: true
})
    // .setLngLat([51.3890, 35.6892])
    .setLngLat([51.3890, 35.6892])

    .addTo(map);

function onDragEnd() {
   var lngLat = marker.getLngLat();
   coordinates.style.display = 'block';
   coordinates.innerHTML = 'Longitude: ' + lngLat.lng +
    '<br />Latitude: ' + lngLat.lat;
}

marker.on('dragend', onDragEnd);



</script>

</body>
</html>

templates/district_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8">
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in queryset %}
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url}}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{ post.timestamp|timesince}}</div>
                    {% for cat in post.categoreis.all %}
                    <div class="category">
                      <a href="#">{{ cat }}</a>
                    </div>
                    {% endfor %}
                  </div><a href="{{ post.get_absolute_url }}">
                    <h3 class="h4">{{ post.title }}</h3></a>
                  <p class="text-muted">{{ post.overview }}</p>
                  <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                      <div class="title"><span>{{ post.author.user.username}}</span></div></a>
                    <div class="date"><i class="icon-clock"></i>{{post.timestamp|timesince}} ago</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                  </footer>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </main>
        {% include 'sidebar.html' with most_recent=most_recent  category_count=category_count  %}
      </div>
    </div>


 {% endblock content %}

templates/filter_dropdown2.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<style>
  label {
    padding: 10px;
  }
</style>

<div class="jumbotron">
  <div class="container">
    <div style="border: dashed 1px grey;">
      <form id="myForm"
            method="GET"
            class="form-inline"
            data-state="{{ request.GET.state }}"
            data-city="{{ request.GET.city }}"
            data-area="{{ request.GET.area }}"
            >
        <!-- <div class="form-group">
          <label for="stateSelect">State</label>
          {% render_field form.state title="State" class="form-control" %}
        </div> -->

        <div class="form-group">
          <label for="citySelect">City</label>
          {% render_field form.city title="City" class="form-control" %}
        </div>

        <div class="form-group">
          <label for="areaSelect">Area</label>
          {% render_field form.area title="Area" class="form-control" %}
        </div>

        <div class="form-group">
          <button id="btnSubmit" class="btn btn-success" type="submit">submit</button>
        </div>
      </form>
    </div>

  </div>
</div>




{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function() {
      let state = $('#myForm').data('state')
      let city = $('#myForm').data('city')
      let area = $('#myForm').data('area')
      if (state) {
        $('#id_state option[value='+state+']').attr('selected', 'selected');
      }
      if (city) {
        $('#id_city option[value='+city+']').attr('selected', 'selected');
      }
      if (area) {
        $('#id_area option[value='+area+']').attr('selected', 'selected');
      }
    });

    $('#id_state').on('change', function() {
      $('#btnSubmit').click();
    });

    $('#id_city').on('change', function() {
      $('#btnSubmit').click();
    });
  </script>
{% endblock js %}

templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<form method = "POST" action='.'>
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" name="submit">
</form>

{% endblock content %}

templates/form_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

  <h2>Post Form</h2>
<div class = container>
  <div class="row">
  <form method="post" enctype='multipart/form-data' id="postForm"  data-categories-url="{% url 'ajax_load_categories' %}"  data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form|crispy }}
    </table>
    <button type="submit">Save</button>
    <!-- <a href="{% url 'post_changelist' %}">Nevermind</a> -->
  </form>


  </div>
</div>

<!--  -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_city").change(function () {
      var url = $("#postForm").attr("data-cities-url");
      var cityId = $(this).val();
      // var categoryId = $(this).val();


      $.ajax({
        url: url,
        data: {
          'city':cityId
          // 'category':categoryId


        },
        success: function (data) {
          $("#id_area").html(data);
          // $("#id_instance").html(data);

        }
      });

    });
    //
    $("#id_category").change(function () {
      var url = $("#postForm").attr("data-categories-url");
      var categoryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'category':categoryId

        },
        success: function (data) {
          $("#id_instance").html(data);
        }
      });

    });
  </script>
  <!-- <script>

    $("#id_category").change(function () {
      var url = $("#postForm").attr("data-cities-url");
      var categoryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'category':categoryId

        },
        success: function (data) {
          $("#id_instance").html(data);
        }
      });

    });
  </script> -->

{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Exemplo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
  
      <li class="nav-item">
        <a class="nav-link" href="{% url 'filter_dropdown2' %}">Filtrando com dropdown com Django Forms</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>

templates/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<br><br><br><br>
<div class="content-section">
  <form method = "POST" action='.'>
     {% csrf_token %}
     <fieldset class="border-bottom mb-4">Reset Password</legend>
       {{ form }}
     <div class ="form-group">
       <button class="btn btn-outline-info" type="submit">Request Password Reset </button>
     </div>
  </form>
</div>
<br><br><br><br>
{% endblock content %}